FROM node:14.10.1-buster

LABEL "com.github.actions.name"="build"
LABEL "com.github.actions.description"="Compile SCSS"
LABEL "repository"="http://github.com/TalBrenev/complex-grapher"
LABEL "maintainer"="Tal Brenev <tal.brenev@gmail.com>"

RUN npm install -g sass
