FROM python:3

LABEL "com.github.actions.name"="deploy"
LABEL "com.github.actions.description"="Deploy to S3"
LABEL "repository"="http://github.com/TalBrenev/complex-grapher"
LABEL "maintainer"="Tal Brenev <tal.brenev@gmail.com>"

RUN apt update
RUN pip install awscli
