FROM clojure:openjdk-11-lein-2.9.1-stretch

LABEL "com.github.actions.name"="test"
LABEL "com.github.actions.description"="Run CLJS tests"
LABEL "repository"="http://github.com/TalBrenev/complex-grapher"
LABEL "maintainer"="Tal Brenev <tal.brenev@gmail.com>"
