FROM clojure:openjdk-8-lein-2.9.3-slim-buster

LABEL "com.github.actions.name"="test"
LABEL "com.github.actions.description"="Run CLJS tests"
LABEL "repository"="http://github.com/TalBrenev/complex-grapher"
LABEL "maintainer"="Tal Brenev <tal.brenev@gmail.com>"

RUN apt update && apt -y install nodejs
