name: Release

on:
  push:
    tags:
      - v[0-9]*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: build
      uses: ./.github/build
      with:
        entrypoint: ./.github/build/run.sh

    - name: deploy
      uses: ./.github/deploy
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      with:
        entrypoint: ./.github/deploy/run.sh
