name: Test

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: test
      uses: ./.github/test
      with:
        entrypoint: ./.github/test/run.sh
